### ISSUE TITLE
Stebalien's TODO

### ISSUE THREAD

**Issue by Stebalien** [ipfs/go-libp2p-transport#23]
* [x] Remove `DialContext` and add a context parameter to `Dial`.
* [ ] Add a `SetAddrFilters` method to `Listener`. Let's push this down as far as we can go.
* [ ] Figure out naming. This package is really really "multiaddr transports". `go-libp2p-interface-conn` is the equivalent for p2p transports.

**Comment by Stebalien** [comment]
Nonsensical due to the refactor.
